# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install python3 testing dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Install R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.1.2'
    - name: Install R dependencies
      run: |
        R -e "install.packages(c('Matrix'))"
        R -e "install.packages(c('car'))"
        R -e "install.packages(c('carData'))"
        R -e "install.packages(c('lme4'))"
    - name: Install python3 FiNN dependencies #dependencies are installed here to make sure R is found
      run: |
        pip install -r requirements.txt
    - name: Build & install FiNN
      run: |
        pip install build
        python -m build
        python -m pip install .
    - name: Test with unittest
      run: |
        python -m unittest discover -s finn/tests/ -p "*.py"
